[project]
name = "typespecs"
version = "0.1.0"
description = "Data specifications by type hints"
readme = "README.md"
keywords = ["dataclasses", "specifications", "typing"]
requires-python = ">=3.10,<3.15"
dependencies = [
    "pandas>=2,<3",
    "pandas-stubs>=2,<3",
    "typing-extensions>=4,<5",

]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]

[[project.authors]]
name = "Akio Taniguchi"
email = "taniguchi.akio@gmail.com"

[project.license]
file = "LICENSE"

[project.urls]
homepage = "https://astropenguin.github.io/typespecs/v0.1.0"
repository = "https://github.com/astropenguin/typespecs"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "black>=25,<26",
    "ipython>=8,<10",
    "myst-parser>=3,<5",
    "pyright>=1,<2",
]

[tool.pyright]
typeCheckingMode = "strict"
